const restaurants = ()=>{
    return [
        {
          id: 1,
          name: "Tasty Burger",
          cuisine: "American",
          rating: 4.5,
          foods: [
            "Burger",
            "Fries",
            "Milkshake",
            "Chicken Sandwich",
            "Onion Rings",
            "Salad",
            "Hot Dog",
            "Fish and Chips",
            "Cheeseburger",
            "Soda",
            "Ice Cream",
            "Nachos",
            "Wings",
            "Wrap",
            "Pancakes",
            "French Toast",
            "Hash Browns",
            "Chicken Tenders",
            "Quesadilla",
            "BBQ Ribs",
            "Pizza",
          ],
        },
        {
          id: 2,
          name: "Spice Bazaar",
          cuisine: "Indian",
          rating: 4.0,
          foods: [
            "Curry",
            "milk",
            "Naan",
            "Biryani",
            "Tandoori Chicken",
            "Samosa",
            "Raita",
            "Paneer Tikka",
            "Dosa",
            "Pakora",
            "Chaat",
            "Gulab Jamun",
            "Jalebi",
            "Korma",
            "Lassi",
            "Chutney",
            "Bhaji",
            "Bhel Puri",
            "Pav Bhaji",
            "Vada",
            "Rice",
            "Kebab",
            "Paratha",
          ],
        },
        {
          id: 3,
          name: "Sushi Palace",
          cuisine: "Japanese",
          rating: 4.8,
          foods: [
            "Sushi",
            "Sashimi",
            "Miso Soup",
            "Tempura",
            "Ramen",
            "Teriyaki",
            "Udon",
            "Nigiri",
            "Rolls",
            "Edamame",
            "Yakitori",
            "Wasabi",
            "Gyoza",
            "Tempura",
            "Chirashi",
            "Sake",
            "Tofu",
            "Donburi",
            "Sunomono",
            "Takoyaki",
            "Okonomiyaki",
            "Matcha",
          ],
        },
      ]
}

module.exports = restaurants